repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.3
    hooks:
      - id: ruff
        args: [--fix]
        files: ^bindings/diffsol-pytorch/.*\.py$
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.1
    hooks:
      - id: mypy
        files: ^bindings/diffsol-pytorch/python/.*\.py$
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
        files: ^(README\.md|docs/|bindings/diffsol-pytorch/|scripts/)
      - id: trailing-whitespace
        files: ^(README\.md|docs/|bindings/diffsol-pytorch/|scripts/)
